beauty/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/index', to: 'home#index'

  get '/abouts', to: 'home#abouts'

  get '/blogs', to: 'home#blogs'

  get '/contactus', to: 'home#contactus'

  get '/search', to: 'home#search'

  resources :products

  resources :services

  resources :orders

  resources :appointments

    root to: 'home#index'
end

beauty/app/models/service.rb
class Service < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50}
  validates :price, numericality: true
  validates :description, length: { minimum: 5, maximum: 500 }

  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
end

beauty/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    page = params[:page].to_i > 0 ? params[:page] : 1
    @services = Service.page(page).per(6)
    @services = @services.where('services.name like ?', "%#{params[:name]}%") if params[:name].present?
  end
end

beauty/app/views/services/index.html.erb
  <div class="ftco-blocks-cover-1">
    <div class="site-section-cover overlay" data-stellar-background-ratio="0.5" style="background-image: url('assets/hom_1.jpg')">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-7">
              <h1 class="mb-3">Our Services</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta veritatis in tenetur doloremque, maiores doloribus officia iste. Dolores.</p>
              <p><a href="#" class="btn btn-primary">Learn More</a></p>
              <%= form_tag services_path,method: :get do %>
                <div>
                  <%= text_field_tag :name ,params[:name], placeholder: "Search Services" ,class: "form-control" %><br>
                  <%= submit_tag "Search", class: "btn btn-primary " %>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <table class="text-center text-dark table table-hover">
    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <% @services.each do |service| %>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="<%= service_path(service) %>">
                <img src="/assets/haircut2.jpg" alt="Image" class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                <h2><a href="<%= service_path(service) %>"><%= service.name %></a></h2>
                <!-- <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span> -->
                <p><%= service.description %></p>
                <div>
                  <button class="btn btn-outline-primary custom-prev"><%= link_to 'Appointment', new_appointment_path %></button>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <%= paginate @services %>
      </div>
      </div>
  </table>
</div>

beauty/app/views/services/show.html.erb
<div class="site-wrap" id="home-section">
  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>

  <div class="ftco-blocks-cover-1">
    <div class="ftco-cover-1 innerpage overlay" style="background-image: url('/assets/hom_1.jpg')">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-lg-6 text-center">
            <span class="d-block mb-3 text-white" data-aos="fade-up">July 17, 2019 <span class="mx-2 text-primary">&bullet;</span> by James Miller</span>
              <h1 class="mb-4" data-aos="fade-up" data-aos-delay="100">service</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5 mb-lg-0">
          <div class="img-years">
            <img src="/assets/haircut1.jpg" alt="Image" class="img-fluid">
          </div>
          <blockquote><p>dcskfskvnsdk</p></blockquote>
          <p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
        </div>
        <div class="col-md-6 sidebar">
          <div class="sidebar-box">
            <div class="categories">
              <h3>Categories</h3>
              <li><a href="/products">Hair Treatment <span>(12)</span></a></li>
              <li><a href="/products">Nail Treatment <span>(22)</span></a></li>
              <li><a href="/products">Facials & Skin Care Treatment <span>(37)</span></a></li>
              <li><a href="/products">Tattoo Treatment<span>(42)</span></a></li>
              <li><a href="/products">Hair Removal <span>(14)</span></a></li>
              <li><a href="/products">Massages <span>(14)</span></a></li>
            </div>
          </div>
          <div class="sidebar-box">
              <div class="row  mb-5">
                <div class="col-md-12 text-center">
                  <div class="row">
                  <p class=" col-md-6 text-center">
                    <button class="btn btn-outline-primary custom-prev"><%= link_to 'Appointment', new_appointment_path %></button>
                  </p>
                </div>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>