SALOON/config/routes.rb
Rails.application.routes.draw do
  resources :publics
  resources :authors
  resources :books
  resources :appointments
  resources :order_products
  resources :orders
  resources :products
  resources :categories
  resources :services
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

SALOON/app/models/order_product.rb
class OrderProduct < ApplicationRecord
  validates :price, numericality: true
  validates :discount, numericality: true
  validates :total, numericality: true

  belongs_to :order
  belongs_to :product
end

SALOON/app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :set_order_product, only: [:show, :edit, :update, :destroy]

  # GET /order_products
  # GET /order_products.json
  def index
    @order_products = OrderProduct.all
  end

  # GET /order_products/1
  # GET /order_products/1.json
  def show
  end

  # GET /order_products/new
  def new
    @order_product = OrderProduct.new
  end

  # GET /order_products/1/edit
  def edit
  end

  # POST /order_products
  # POST /order_products.json
  def create
    @order_product = OrderProduct.new(order_product_params)

    respond_to do |format|
      if @order_product.save
        format.html { redirect_to @order_product, notice: 'Order product was successfully created.' }
        format.json { render :show, status: :created, location: @order_product }
      else
        format.html { render :new }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_products/1
  # PATCH/PUT /order_products/1.json
  def update
    respond_to do |format|
      if @order_product.update(order_product_params)
        format.html { redirect_to @order_product, notice: 'Order product was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_product }
      else
        format.html { render :edit }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_products/1
  # DELETE /order_products/1.json
  def destroy
    @order_product.destroy
    respond_to do |format|
      format.html { redirect_to order_products_url, notice: 'Order product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product
      @order_product = OrderProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_product_params
      params.require(:order_product).permit(:product_id, :order_id, :price, :discount, :discount_type, :total)
    end
end

SALOON/app/helpers/order_products_helper.rb
module OrderProductsHelper
end

SALOON/app/views/order_products/_form.html.erb
<%= form_with(model: order_product, local: true) do |form| %>
  <% if order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
        <% order_product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :discount_type %>
    <%= form.text_field :discount_type %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

SALOON/app/views/order_products/edit.html.erb
<h1>Editing Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

SALOON/app/views/order_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Price</th>
      <th>Discount</th>
      <th>Discount type</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_products.each do |order_product| %>
      <tr>
        <td><%= order_product.product_id %></td>
        <td><%= order_product.order_id %></td>
        <td><%= order_product.price %></td>
        <td><%= order_product.discount %></td>
        <td><%= order_product.discount_type %></td>
        <td><%= order_product.total %></td>
        <td><%= link_to 'Show', order_product %></td>
        <td><%= link_to 'Edit', edit_order_product_path(order_product) %></td>
        <td><%= link_to 'Destroy', order_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Product', new_order_product_path %>

SALOON/app/views/order_products/new.html.erb
<h1>New Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Back', order_products_path %>

SALOON/app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_product.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_product.order_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order_product.price %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @order_product.discount %>
</p>

<p>
  <strong>Discount type:</strong>
  <%= @order_product.discount_type %>
</p>

<p>
  <strong>Total:</strong>
  <%= @order_product.total %>
</p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>